[Build]
ToolsTree=default

[Distribution]
Distribution=debian
Release=unstable

[Content]
MakeInitrd=no
Bootloader=uki
Packages=systemd
        linux-image-amd64
        systemd-boot-efi

[Output]
Format=uki
ImageId=test
