name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-uefi
        override: true

    - name: Build UEFI binary
      run: |
        cargo build --release --target x86_64-unknown-uefi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi debian-sid.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi debian-trixie.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi ubuntu-25.10.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi ubuntu-25.04.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi ubuntu-24.10.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi ubuntu-24.04.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi fedora-42.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi fedora-41.efi
        cp ./target/x86_64-unknown-uefi/release/poweroff.efi fedora-40.efi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./*.efi
        retention-days: 30
